### PR TITLE
Creating log folder

### PR DESCRIPTION
**Pull request by AnsgarSchmidt**

### CODE REVIEW

**Comment by SettRaziel** [comment]
Addressed the issue with the log folder with https://github.com/SettRaziel/wrf_archlinux/commit/38d7804bf85bb08a12c47ed62d86332c27c822c5.

Normally the gfs data folder is created when using the deployment scripts along with the required output folder, see https://github.com/SettRaziel/wrf_archlinux/blob/development/wrf_deploy/create_directories.sh .

**Comment by AnsgarSchmidt** [comment]
Ah, ok. I thought wrf_deploy is only to be used at workshops and not for production.
To the workflow is:
1. edit wrf_install/install_wrf.sh (the installation path)
2. run install_wrf.sh
3. Download WPS_GEOG files 
4. wrf_deploy/deploy_wrf.sh
5. edit wrf_run/run_model.sh (the installation path)
6. run run_model.sh

It's a little bit complicated. If you want I can help you writing a howto file for newbies like me. 
We could have a call on the weekend and make a new installation and document the process.

Greetings
Ansgar

**Comment by SettRaziel** [comment]
I am afraid we have a major misunderstanding here. The workflow is not the one you noted in your comment.
You have the option to either install the model by yourself by compiling the WRF model / WPS model and all the required libraries with the help of scripts within wrf_install. Doing that there are several steps to do to run the model successfully.
The other option is to use the scripts within wrf_deploy. As stated in the readme file the wrf_deploy downloads an already precompiled archive with all required software components (basically when installing with wrf_install a successful compile lead to a tar.gz which could be deployed by the deploy scripts).
The deployment contains:
* creation of the required folder
* installing the required packages for a model run
* download of the selected geo data and unzipping of the archives
* download of the selected precompiled wrf and unzipping of the archive

It is correct that i am missing the setting of the geo data within the namelist.WPS. But the idea is to create a ticket that creates an adds a script that will check if the manual steps that a required are correct or if there is need of manual interaction.
So the only step that is neccessary at the moment (when using the deploy scripts) is to set the namelist.WPS and the run_model parameters.
I have specifc plans to fix that, but i need some more time for that.

**Comment by AnsgarSchmidt** [comment]
Ok, thanks for the clarification. 
My offer still exists to help you with documentation and if you want with scripting. 
If you want to do it all alone also fine, just let me know. :-)

**Comment by SettRaziel** [comment]
Thanks for the offering. I will take that, but for some things i have to make some more brainstorming before knowing in which detail i want to have it :).

**Pull request closed without merging**
